---
 - hosts: "{{ target_host }}"
   become: true
   tasks:
     - name: install clameAv
       ansible.builtin.command:
         cmd: apt install  clamav clamav-daemon -y
       register: PackageLog
     - name: stop the freshclam
       ansible.builtin.command:
         cmd: systemctl stop clamav-freshclam
         cmd: freshclam
         cmd: systemctl start clamav-freshclam

     - name: dump it to the file
       ansible.builtin.lineinfile:
         path: "/tmp/EmpsystemLog/group4/{{ inventory_hostname }}_{{ lookup('pipe', 'date +%Y%m%d_%H%M%S') }}_package.log"
         line: "Installing ClamAV: \n\n{{ PackageLog.stdout_lines | join('\n') }}"

         create: yes
       delegate_to: localhost

#Installing ClamAV: \n\n{{ PackageLog.stdout_lines | join('\n') }}
