---
 - hosts: "{{ target_host }}"
   become: yes
   tasks:
    - name: Find .sql files
      ansible.builtin.command:
        cmd: sudo find / -type f -name "*.sql"      
      register: sql_files
      ignore_errors: true   
    
    - name: Find .sql.gz files
      ansible.builtin.command:
        cmd: sudo find / -type f -name "*.sql.gz"      
      register: sql_gz_files
      ignore_errors: true
    
    - name: grab the sql name
      ansible.builtin.command:
        cmd: basename "{{ item }}"
      register: sql_names
      with_items: "{{ sql_files.stdout_lines }}"
      
    - name: grab the sql.gz name
      ansible.builtin.command:
        cmd: basename "{{ item }}"
      register: sql_gz_names
      with_items: "{{ sql_gz_files.stdout_lines }}"
      
    - name: Exclude the default
      ansible.builtin.set_fact:
        sqlgz: "{{ sql_gz_names.results | map(attribute='stdout') | list }}" 

    - name: Exclude the default
      ansible.builtin.set_fact:
        sql: "{{ sql_names.results | map(attribute='stdout') | list }}"         
             
    - name: Print the database name
      ansible.builtin.debug:
        msg: "{{ sql }}"

    - name: Print the database name
      ansible.builtin.debug:
        msg: "{{ sqlgz }}"        
      
