---
- hosts: "{{ target_host }}"
  become: yes
  tasks:
    - name: system update
      ansible.builtin.command:
        cmd: apt-get update -y
      register: updateLog
      ignore_errors: true

    - name: upgrade packages
      ansible.builtin.command:
        cmd: apt-get upgrade -y
      register: upgradeLog
      ignore_errors: true

    - name: dist-upgrade packages
      ansible.builtin.command:
        cmd: apt-get dist-upgrade -y
      register: distUpgradeLog
      ignore_errors: true

    - name: dump it to the file
      ansible.builtin.lineinfile:
        path: "/tmp/{{ inventory_hostname }}_{{ lookup('pipe', 'date +%Y%m%d_%H%M%S') }}_package.log"
        line: "\n\n ----------------------- {{ lookup('pipe', 'date +%Y%m%d') }} ----------------------- \n\nCACHE UPDATE: \n\n{{ updateLog.stdout_lines | join('\n') }}\n\nPACKAGE UPGRADE: \n\n {{ upgradeLog.stdout_lines | join('\n') }}\n\n DIST UPGRADE: \n\n {{ distUpgradeLog.stdout_lines | join('\n') }} "
        create: yes
      delegate_to: localhost
      run_once: true
      #loop: "{{ ansible_play_hosts }}"
      #loop_control:
      #  loop_var: hosts
      
      
 
 

