---
- hosts: "{{ target_host }}"
  become: true
  vars:
    max_days: "{{ 90 }}"
    min_days: "{{ 2 }}"
#    login_def: "{{ /etc/login.defs }}"
  tasks:
    - name: Set password validity
      ansible.builtin.user:
        name: "{{ user_name }}"
        password_expire_max: "{{ max_days }}"
        password_expire_min: "{{ min_days }}"

    - name: View change for "{{ user_name }}"
      ansible.builtin.command:
        cmd: sudo chage -l "{{ user_name }}"
      register: PasswordAge

    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: /tmp/testing
        dest: /tmp/testing_bkp

    - name: Generate log information
      ansible.builtin.lineinfile:
        path: /tmp/testing
        regexp: '{{item.From}}'
        line: '{{item.To}}'
        state: present
      with_items:
       - { From: 'PASS_MAX_DAYS   99999', To: 'PASS_MAX_DAYS   90'}
       - { From: 'PASS_MIN_DAYS   0', To: 'PASS_MIN_DAYS   7'}

    - name: diff btn file
      ansible.builtin.command:
        cmd: diff /tmp/testing /tmp/testing_bkp
      register: diffOutput
      ignore_errors: true

    - name: lock the file
      ansible.builtin.command:
        cmd: chattr +i /tmp/testing
        
    - name: Install libpam-pwquality Package
      ansible.builtin.command:
        cmd: apt-get install -y libpam-pwquality
      register: lipLog
      
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: /tmp/common-password
        dest: /tmp/common-password_bkp
        
    - name: add a line using echo
      ansible.builtin.lineinfile:
        path: "/tmp/common-password"
        line: "password requisite pam_pwquality.so retry=3 minlen=9 lcredit=-1 ucredit=-1 dcredit=-2 ocredit=-1 maxrepeat=5  gecoscheck  maxclassrepeat=6 difok=2"

    - name: diff btn file
      ansible.builtin.command:
        cmd: diff /tmp/common-password /tmp/common-password_bkp
      register: diffOutputCP
      ignore_errors: true

    - name: lock the file
      ansible.builtin.command:
        cmd: chattr +i /tmp/common-password
        
    - name: Generate log information
      ansible.builtin.lineinfile:
        path: "/tmp/{{ inventory_hostname }}_{{ lookup('pipe', 'date +%Y%m%d') }}_OS.log"
        line: "\n\n-----------------{{ lookup('pipe', 'date +%d/%m/%Y_%H:%M:%S') }}-----------------\n\nPASSWORD VALIDITY:\n\n{{ PasswordAge.stdout }}\n\n DIFFRENCE BETWEEN Password FILES:\n\n {{ diffOutput.stdout }}\n\n libpam-pwquality:\n\n {{ lipLog.stdout }}\n\n  DIFFRENCE BETWEEN COMMON PASSWORD FILES:\n\n{{ diffOutputCP.stdout }}"
        create: yes
      delegate_to: localhost
