---
- hosts: "{{ target_host }}"
  become: true
  tasks:
  - name: Mysql Version
    ansible.builtin.command:
      cmd: sudo apt-get remove update-notifier -y
#   register: clamAv
    ignore_errors: True

 # - name: print the output of clamAv
 #   ansible.builtin.debug:
 #     msg: "{{ clamAv.stdout }}"
