---
- hosts: "{{ target_host }}"
  become: true
  tasks:
  - name: Mysql Version
    ansible.builtin.command:
      cmd: sudo chattr -i /etc/modprobe.d/blacklist.conf
      cmd: sudo cp -p /etc/modprobe.d/blacklist.conf .
      cmd: sudo update-initramfs -u
      cmd: sudo chattr +i /etc/modprobe.d/blacklist.conf
      cmd: sudo modprobe - r usb_storage
      cmd: sudo modprobe - r uas
      cmd: sudo chattr +i /etc/modprobe.d/blacklist.conf
#   register: clamAv
    ignore_errors: True

 # - name: print the output of clamAv
 #   ansible.builtin.debug:
 #     msg: "{{ clamAv.stdout }}"
